# Generated by Django 5.2.4 on 2025-08-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
