# Generated by Django 5.2.4 on 2025-09-09 14:06

from django.db import migrations

def fix_order_status(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    Order.objects.filter(status='Not_paid').update(status='Not Paid')
    Order.objects.filter(status='Ready_To_Ship').update(status='Ready To Ship')

class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(fix_order_status),
    ]
