# Generated by Django 5.2.4 on 2025-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not_paid', 'Not_paid'), ('Ready_To_Ship', 'Ready_To_Ship'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Not_paid', max_length=20),
        ),
    ]
