# Generated by Django 5.2.4 on 2025-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='totla_price',
            field=models.DecimalField(decimal_places=2, default=100.05, max_digits=12),
            preserve_default=False,
        ),
    ]
