# Generated by Django 5.2.4 on 2025-08-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='totla_price',
            new_name='total_price',
        ),
    ]
